# Generated by Django 5.1.4 on 2025-01-02 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trader_log", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trade",
            old_name="entry_price",
            new_name="price",
        ),
        migrations.RemoveField(
            model_name="trade",
            name="exit_price",
        ),
    ]
